version: "3"

services:
  app:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
    command: sleep infinity
    ports:
      - "5555:5555"
    volumes:
      - ./:/workspace
      - ./gradle-docker:/home/vscode/.gradle
